// Generated by CoffeeScript 1.7.1
(function() {
  var WebRTCInterop;

  WebRTCInterop = (function() {
    function WebRTCInterop() {}

    WebRTCInterop.infectGlobal = function() {};

    return WebRTCInterop;

  })();

  module.exports = WebRTCInterop;

}).call(this);
