// Generated by CoffeeScript 1.7.1
(function() {
  var WebRTCInterop;

  WebRTCInterop = (function() {
    function WebRTCInterop() {}

    WebRTCInterop.infectGlobal = function() {
      var _ref;
      return global.RTCPeerConnection = (_ref = global.RTCPeerConnection) != null ? _ref : global.webkitRTCPeerConnection;
    };

    return WebRTCInterop;

  })();

  module.exports = WebRTCInterop;

}).call(this);
